### ISSUE TITLE
why do you use Vertx

### ISSUE THREAD

**Issue by FishingZVVZ** [ozkanpakdil/test-microservice-frameworks#549]
Hi, Why do you use Vertx, are you using reactive programming, why dont you use Webflux in Spring. What is the difference between Vertx and Webflux when talking about Reactive Programming

**Comment by ozkanpakdil** [comment]
**Why do you use Vertx** : I use vertx to compare with others. this app is testing all different frameworks you can see the graphic 
![image](https://user-images.githubusercontent.com/604405/214153589-f372b341-820f-482b-9e61-d0e6686f5226.png)

**are you using reactive programming** : yes sometimes.

** why dont you use Webflux in Spring** : I think code has webflux here https://github.com/ozkanpakdil/test-microservice-frameworks/blob/main/spring-boot-webflux/pom.xml

 **What is the difference between Vertx and Webflux when talking about Reactive Programming** Vertx has more light framework, spring is little bit heavy
